### ISSUE TITLE
Issue with sun.misc.Unsafe

### ISSUE THREAD

**Issue by homacs** [JOML-CI/JOML#101]
Hi there!

There is a weird issue related to Unsafe. It occurs when an object (such as Quaternionf) is instantiated and used in the same method AND the method has been optimized by the JIT compile to level C2.
Somehow the method using the object can't see the modifications that have been done by methods of Unsafe such as Unsafe.putLong(). This is probably a bug in the JIT compiler, but I think you will be interested anyway.

I have set up a test environment with two classes which demonstrates the issue. Since it occurs only if the method is optimized to C2 it takes a while until you will see the bug (up-to a minute).

Test environment: https://github.com/homacs/UnsafeBug

System and lib I used:
Java "1.8.0_101" HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
Linux 4.4.0-59-generic #80-Ubuntu x86_64
JOML 1.9.1

I've tried a lot of things to find a fix such as using memory fences, but there is none but turning of the use of Unsafe, unfortunately. At least for me, it is possible that this is system specific.

Kind regards
 Holger

**Comment by httpdigest** [comment]
Hi Holger,

first of all, thanks for the very detailed description with the reproducible test case. The error occurred immediately when I executed your test case with assertions enabled.

In fact, I've seen this strange bug before, which was the reason `Unsafe.putOrderedLong()` is used (when available) instead of `Unsafe.putLong()`, which seemed to have fixed the issue I've seen in the past.

For some reason, this "fix" did not work in this case.
A _workaround_ seems to just not use Unsafe in the constructor. When I change the constructor of Quaternionf to just `this.w = 1.0f;` (which is also faster), then this particular issue does not occur with me anymore. Even when I immediately afterwards use `Quaternionf.identity()` with Unsafe.
This of course is only a workaround, that might break in other situations, because I currently don't know what exactly is happening there.

I'll investigate further.

Kai

**Comment by httpdigest** [comment]
I could reduce the reproducible test case to just this single file:
```Java
import org.joml.Quaternionf;
public class Main {
	public static void main(String[] args) {
		while (true) {
			Quaternionf orientation = new Quaternionf(0, 0, 0, 0);
			orientation.identity();
			if (orientation.w == 0.0f) {
				throw new AssertionError();
			}
		}
	}
}
```

**Comment by homacs** [comment]
I'm sorry to say this but the fix you used does not work always. I tried it before. 
And, btw, it also happens, if you use putOrderedLong() .. this it what is used on my machine.
I will analyse the assembler code (with pen and paper) to find out what actually happens. When you look at the code, you see that the compiler has special optimisation strategies for Unsafe methods. putLong etc. are actually fully inlined (a single MOV instruction instead of a function CALL) even though they are native methods. That makes me believe that the Oracle guys made a mistake in one of those special cases. I will file a bug report when I'm done.

**Comment by httpdigest** [comment]
Some findings that might help you: I really suspect escape analysis. It seems that when escape analysis eliminates object allocation and promotes fields to stack memory (or even registers) it will check how fields are written to and how they are being read. It seems that Unsafe writes are probably not going to be promoted to the same stack memory / register writes, when we write using a wider move instruction than the field being checked by escape analysis.
For example, the following works:
```Java
import org.joml.Quaternionf;
public class Main {
    static Quaternionf orientation = new Quaternionf(0, 0, 0, 0);
    public static void main(String[] args) throws InterruptedException {
        while (true) {
            orientation.set(0, 0, 0, 0);
            orientation.identity();
            if (orientation.w == 0.0f) {
                throw new AssertionError();
            }
        }
    }
}
```
I'm glad you try to figure this out. But don't put too much energy into it, since I really think Oracle will never fix this. Not in JDK9 at least and neither in JDK10, then they are planning to eliminate sun.misc.Unsafe altogether.

**Comment by httpdigest** [comment]
It seems escape analysis respects Unsafe writes to exactl object field offsets. Try to change MemoryUtilUnsafe.identity(Quaternionf) to:
```Java
UNSAFE.putOrderedLong(dest, Quaternionf_x+4, 0x3F80000000000000L);
```
So effectively setting only y to 0 and z to 1.
Then use the following test case:
```Java
            Quaternionf orientation = new Quaternionf(0, 0, 1, 0);
            orientation.identity();
            if (orientation.z == 0.0f) {
                throw new AssertionError();
            }
```
Here, C2 seems to identify that a Unsafe write was only done to the field y. But since y is not being used at all in the test code, it eliminates the Unsafe write altogether, leaving z still being 0.

**Comment by homacs** [comment]
Yes, I know. But I hope they will fix it for 1.7 and 1.8 at least.

**Comment by httpdigest** [comment]
Wow. Another strange thing: When using `Unsafe.putLong()` instead of `Unsafe.putOrderedLong()` the issue does not appear with me. (using JDK8_112, Win 7 x64).

**Comment by homacs** [comment]
You mean, you have to issue a putFloat() for every member variable? That could make sense, if they just consider memory elements on the granularity defined in the java class.

**Comment by httpdigest** [comment]
I mean using `Unsafe.putLong()` instead of using `Unsafe.putOrderedLong()`.
And yes, using `Unsafe.putFloat()` for every member always worked, and is just as fast as a direct field write with assignment.

**Comment by homacs** [comment]
Yeah, my statement was actually for your previous previous reply. I will test with putLong too. I might be, that "Ordered" in this case actually mean .. loosen the order to achieve more speed.

**Comment by homacs** [comment]
I've tested.
1. You small test case (see your 3rd reply) did not fail with putOrderedLong on my machine but with putLong.
2. In my case it was exactly the opposite. It fails with putOrderedLong and does not fail with putLong.

**Comment by httpdigest** [comment]
That is indeed very strange. It's probably time to file that bug report. :)

For final reference: This would be my self-contained test case:
```Java
package tiny;

public class Main {
    /**
     * Test class. We would like to use a MOVQ to set both x and y to 0.0f and 1.0f, respectively.
     * We do this by using Unsafe.putLong (or putOrderedLong). See below.
     */
    private static class Vector2 {
        public float x;
        public float y;
    }

    static final sun.misc.Unsafe UNSAFE;
    static final long Vector2_x;
    static {
        try {
            java.lang.reflect.Field field = sun.misc.Unsafe.class.getDeclaredField("theUnsafe");
            field.setAccessible(true);
            UNSAFE = (sun.misc.Unsafe) field.get(null);
            Vector2_x = UNSAFE.objectFieldOffset(Vector2.class.getDeclaredField("x"));
        } catch (Exception e) {
            throw new AssertionError(e);
        }
    }

    public static void main(String[] args) throws InterruptedException {
        // Create bit pattern for least significant 32-bits = 0.0f and most significant 32-bits = 1.0f
        long highOneLowZero = ((long) Float.floatToRawIntBits(1.0f)) << 32L;
        while (true) {
            Vector2 v = new Vector2();
            // On JDK8_112, Win7 x64, the following fails:
            UNSAFE.putOrderedLong(v, Vector2_x, highOneLowZero);
            // on the same maching the following works:
            //UNSAFE.putLong(v, Vector2_x, highOneLowZero);
            if (v.y == 0.0f) {
                throw new AssertionError();
            }
        }
    }
}
```

**Comment by homacs** [comment]
thats great. I'll use it to send it in.

**Comment by homacs** [comment]
or do you file the report?

**Comment by httpdigest** [comment]
I think, in order to file a bug report, you have to be a OpenJDK/JCP member. I was assuming you were. At least, when I once wanted to file a bug, I've given up because I could not find how.

**Comment by httpdigest** [comment]
Can you tell me whether my last example works for you (either putLong or putOrderedLong) including the exact OS version so that I can submit to http://bugreport.java.com/? It seems at least with Oracle Java it is easy to file a bug.

**Comment by homacs** [comment]
yep. wait a second.

**Comment by homacs** [comment]
Assertion fails with putOrderedLong here.

I've pasted the disassembly of the main function on pastebin: http://pastebin.com/phv2BHU7

They will need it to analyse the issue.

**Comment by httpdigest** [comment]
Okay, thanks. Do you think you can strip down your example, which fails with `Unsafe.putLong()` for you, to a single file?

**Comment by homacs** [comment]
Can do.

**Comment by homacs** [comment]
It does not work. When I create a tiny example using Unsafe.putLong or putOrderedLong directly, everything is correct. I then added more of your code from MemUtil and Quaternion step by step but it still works. When I strip down the example, I had before, it works as well. This looks like a memory bus timing issue, to be honest. Very hard to reproduce. I suggest to leave it by this simple example and tell them that it is machine dependent whether putLong or putOrderedLong works.

**Comment by homacs** [comment]
memory bus is nonsense since it is all on the stack  :D

**Comment by homacs** [comment]
Hello again!

Did you get a reply on the bug report? Is it a bug or a feature?

Also, it looks like you are going to remove the putLong calls. But, if putXXX() methods guarantee consistency for member variables only - maybe you can store the variables in an array and use putLong on the array instead? Just an idea.

**Comment by httpdigest** [comment]
Hi,
I did not yet submit an issue, because I do not have a consistent set of reproducible examples showing that one case fails with `Unsafe.putLong` and another with `Unsafe.putOrderedLong`. Currently, I can reproduce an error when using `putOrderedLong`, but not with the other one. Therefore, the current JOML code will use `putLong` instead of `putOrderedLong`. Also, overlapping `putLong` is not used anymore for writing POJO fields. Only for reading them for storing into a NIO buffer.
If you can build a reproducible example which fails with `Unsafe.putLong`, we can reconsider an issue report.
