### ISSUE TITLE
Make utility classes non-instantiable and non-inheritable

### ISSUE THREAD

**Issue by ShchAlexander** [JOML-CI/JOML#102]
Can you please make utility classes non-instantiable and non-inheritable?

For example `org.joml.Intersectionf` and  `org.joml.Intersectiond` have only static methods, so they could be refactored to final with private constructor 👍

**Comment by httpdigest** [comment]
I prefer not to do this, because it adds no value other than for the very unlikely case of people actually instantiating such classes by mistake and getting a compiletime-error rather than getting a warning from the IDE when calling static methods through an object.
And people actually subclassing such utility classes is even more unlikely, but not forbidden per se.
