### ISSUE TITLE
JOML-GWT 1.9.2 isn't pushed to OSSRH

### ISSUE THREAD

**Issue by sriharshachilakapati** [JOML-CI/JOML#108]
It seems that JOML-GWT is stuck in 1.9.2-SNAPSHOT in the OSSRH, and 1.9.2 and 1.9.3-SNAPSHOT aren't pushed. Is there any reason for that?

![image](https://cloud.githubusercontent.com/assets/4593204/24296283/860137ba-10c4-11e7-9389-309013cae6bc.png)

**Comment by httpdigest** [comment]
Thanks for the info!
It was just forgotten, since deploying a release isn't an automated process.
The 1.9.2 version of org.joml:joml-gwt has been uploaded and will be available in the next few hours on Maven Central. It will have the exact same feature-level as the 1.9.2 master version.
Also, the latest sources have been deployed as 1.9.3-SNAPSHOT on oss.sonatype.org and are available now.

**Comment by sriharshachilakapati** [comment]
Thank you so much!
