### ISSUE TITLE
Calc normals for indexed faces

### ISSUE THREAD

**Issue by Levvy055** [JOML-CI/JOML#122]
There is already method to calculate normals `GeometryUtils.normal(Vector3f,Vector3f,Vector3f)` but it accept already created Vector3f objects, but what when we are using vbo with float array of vertices and int array of indexes of the object?
Code like this:
```
public static float[] calcNormals(float[] vertices, int[] indices) {
		if (indices.length < 3) {
			float[] normals = new float[]{vertices[3 * indices[0]], vertices[3 * indices[0] + 1], vertices[3 * indices[0] + 2]};
			return normals;
		}
		if (indices.length < 9) {
			Vector3f v0 = new Vector3f(vertices[3 * indices[0]], vertices[3 * indices[0] + 1], vertices[3 * indices[0] + 2]);
			Vector3f v1 = new Vector3f(vertices[3 * indices[1]], vertices[3 * indices[1] + 1], vertices[3 * indices[1] + 1]);
			Vector3f vo1 = new Vector3f();
			Vector3f vo2 = new Vector3f();
			v0.cross(v1, vo1);
			v1.cross(v0, vo2);
			return new float[]{vo1.x, vo1.y, vo1.z, vo2.x, vo2.y, vo2.z};
		}
		HashMap<Vector3f, Vector3f> vecs = new HashMap<>();
		for (int i = 0; i <= indices.length - 3; i += 3) {
			int f0 = indices[i + 0];
			int f1 = indices[i + 1];
			int f2 = indices[i + 2];
			
			float v0x = vertices[3 * f0 + 0];
			float v0y = vertices[3 * f0 + 1];
			float v0z = vertices[3 * f0 + 2];
			
			float v1x = vertices[3 * f1 + 0];
			float v1y = vertices[3 * f1 + 1];
			float v1z = vertices[3 * f1 + 2];
			
			float v2x = vertices[3 * f2 + 0];
			float v2y = vertices[3 * f2 + 1];
			float v2z = vertices[3 * f2 + 2];
			
			Vector3f v0 = new Vector3f(v0x, v0y, v0z);
			Vector3f v1 = new Vector3f(v1x, v1y, v1z);
			Vector3f v2 = new Vector3f(v2x, v2y, v2z);
			
			Vector3f dest = new Vector3f();
			GeometryUtils.normal(v0, v1, v2, dest);
			
			if (!vecs.containsKey(v0)) {
				vecs.put(v0, new Vector3f());
			}
			if (!vecs.containsKey(v1)) {
				vecs.put(v1, new Vector3f());
			}
			if (!vecs.containsKey(v2)) {
				vecs.put(v2, new Vector3f());
			}
			
			vecs.get(v0).add(dest).normalize();
			vecs.get(v1).add(dest).normalize();
			vecs.get(v2).add(dest).normalize();
		}
                float[] normals = new float[vertices.length];
		for (int i = 0; i < indices.length; i++) {
			int ix = 3 * indices[i] + 0;
			int iy = 3 * indices[i] + 1;
			int iz = 3 * indices[i] + 2;
			
			float v0x = vertices[ix];
			float v0y = vertices[iy];
			float v0z = vertices[iz];
			
			Vector3f v0 = new Vector3f(v0x, v0y, v0z);
			Vector3f n = vecs.get(v0);
			
			normals[ix] = n.x;
			normals[iy] = n.y;
			normals[iz] = n.z;
		}
		return normals;
```

**Comment by httpdigest** [comment]
When you have an indexed triangle mesh structure and also want to compute smooth per-vertex normals from the face normals, then using vector objects all over the place is overkill and likely reduces performance needlessly.
Simply copy/use the Vector3f.cross() function + Vector3f.normalize() directly on your floats.
Also, I would not index the vertices by their (x, y, z) position fields via HashMap using Vector3f.equals/hashCode, but simply use the vertex index already given by the indices array.
There are also quite some number of bugs in your code as well, such as in the case of indices.length < 3 you assume the normals of the three vertices to be the vertices themselves, which is clearly wrong. You should just compute and use the face/triangle normal (which is just a special case of your general "compute the average normal of all shared face normals").
Then in the cases < 3 and < 9 you are not normalizing the returned normals.
Then in your last, general case you are not calculating the average normal correctly, because everytime you sum the "so far average" normal and the computed normal, you are immediately normalizing the result, which will give the last touched face normal the biggest weight.
