### ISSUE TITLE
Immutable?

### ISSUE THREAD

**Issue by piegamesde** [JOML-CI/JOML#134]
The `Vector3fc` documentation says:
> Interface to an immutable 3-dimensional vector of single-precision floats

And the docs of `Vector3f#toImmutable` say:
> Create a new immutable view of this {@link Vector3f}.

The problems with this are:
 - If a program takes in a `Vector3fc`, it will assume it is immutable. But you are still free to pass a `Vector3f` as instance of  `Vector3fc` which may have changing values. Even worse, if you happen to access one of those objects, it is possible to cast them back to `Vector3f` and to change the values.
 - If you are aware and use `#toImmutable` instead to make sure it won't be able to get changed, you're wrong too. The proxy returned delegates to the main vector, causing it to change its value with the parent.

I think the documentation should make a differentiation between "immutable" and "read-only", because it says "immutable" and means "read-only" which can be quite confusing and is against common practice. This does apply to large parts of the library, where the `Vector3f` class was just the first one to cause bugs in my code.

And yes, it caused me a lot of pain to find out about this to fix my bug.

**Comment by httpdigest** [comment]
Thanks for your feedback and for bringing this issue to my attention!
I've renamed the `toImmutable()` to `readOnlyView()` to better reflect what that method is doing, and improved the JavaDocs in that regard with the commit: https://github.com/JOML-CI/JOML/commit/1915a6b5c1b13cf64893f7a3da5b81c105432746

It's deployed on oss.sonatype.org now as new 1.9.5-SNAPSHOT version.

**Comment by piegamesde** [comment]
Thanks, this will avoid a lot of confusion to future users.

What about having truly immutable objects? The easiest version would be

    public Vector3fc toImmutable() {
        return new Vector3f(this).readOnlyView();
    }

which would return a Proxy where the delegate has no other reference and thus cannot be changed. Another solution would be to create a new implementation of `Vector3fc` which is immutable and returns a new copy after each operation instead.

**Comment by httpdigest** [comment]
Sure. I've added your suggestion as a new `immutableCopy()` method. I did not want to reuse the old `toImmutable()` method, since it had a different semantics, in case people depended on it.

**Comment by piegamesde** [comment]
I now have the situation that I need a true immutable object and cannot use `immutableCopy()` (because of reasons). What can I do to enforce the values I get are immutable (at compile time, if possible)?

**Comment by httpdigest** [comment]
Generally we always have this: A exposing a vector V via its read-only interface to some other code B. Like you said in your initial post, the two problems are:
a) V is not really immutable since A can modify V through its mutable interface (i.e. the class Vector3f) and B would see the mutation
b) B can mutate V by forcefully casting to its mutable interface and doing the modification

To solve a) A must provide a copy of V to B.
b) can only be solved by letting A provide a copy of V to B where the copy does not implement a mutable interface (i.e. what `immutableCopy()` does when `-Djoml.debug=true`).

If you cannot use the solution for b) then there is no other way. Java simply has no concept of const/immutability built into the language. And everything can always be subverted via Reflection.

Maybe you could elaborate more about your "reasons". Wo are you trying to protect from whom in your code? It's beginning to sound like a pretty hypothetical problem to me.

**Comment by piegamesde** [comment]
The problem: I have a JavaFX property (ObjectProperty<Vector2i>) and want to listen to changes. I want to make sure nobody can change the value by altering its internal state since this would not trigger listeners and bindings and such.

But I think the only viable solution to this (apart from hacking the JavaFX Property implementation) would be to make a new class implementing Vector2i that is truly immutable using final variables set in the constructor. But I don't think it would fit into this library with its "no new objects"-philosophy since it would require to return a new object on each math operation.

**Comment by piegamesde** [comment]
Put that last problem aside -- the code is still problematic:
> (i.e. what immutableCopy() does when -Djoml.debug=true).

This means that `immutableCopy()` returns an immutable copy if `debug=true` and a normal copy (somewhat read-only) if false. So assuming you want to keep that strange `-Djoml.debug` thing in `readOnlyView()`, I suggest changing `immutableCopy()` to not call that method for this reason:

    public Vector2fc immutableCopy() {
        return new Proxy(new Vector2f(this));
    }

**Comment by httpdigest** [comment]
Actually, I am going to remove those immutability/read-only methods from JOML.
It wasn't because of this issue, but because I wanted to do that for a long time now ever since adding it with https://github.com/JOML-CI/JOML/issues/52 in 2015. In my opinion, it does not actually solve any problem and never will, since that problem cannot be solved 100% and is pretty ill-defined anyway.
If you want to have a read-only view on a vector, then expose the vector via its '*c' interface. If someone casts it to the mutable vector class again, it's their fault and they should not complain about why stuff is not working anymore. Even the current solution with the Proxy class provides abolutely no safety at all. If people wanted to, they could always use Reflection to modify the delegate object of the proxy.
If you need a copy of a vector which will not be modified by the provider at least, simply create a copy with the copy constructor. It is clearer because you immediately see that a new vector instance is being created.
Having all those immutable/readonly methods in JOML complicates matters for no good.
I'd like to keep everything very straight and clear like it was in the beginnings of JOML:
- methods on any JOML object mutate that object
- if using the optional `dest` parameter then that object will be modified instead

**Comment by piegamesde** [comment]
I did a quick sketch: https://github.com/piegamesde/JOML/commit/f0c58ee8a08399e8f732578f1bc9a996c1613f37 What do you think about something like this?
