### ISSUE TITLE
Quaternionf.lookAlong() not working as expected

### ISSUE THREAD

**Issue by slyh80** [JOML-CI/JOML#155]
More a question than an issue/bug report.

I tried to use `Quaternionf.lookAlong(...)` to orient an object (camera) towards some target object, expecting it to create an absolute rotation that could for example be used with `Matrix4f.translationRotateScale(V3, Q, V3)` to orient the object towards the target.

When calling the method with identical values on the same Quaternion object multiple times it however bears some result I can not fully grasp. It probably calculates a relative rotation.

In short, I would expect the value of `rotation` in this example to stay the same for both calls to `lookAlong()`:

```
Quaternionf rotation = new Quaternionf();
rotation.lookAlong(0, -3, 10, 0, 1, 0);
rotation.lookAlong(0, -3, 10, 0, 1, 0);
```

Additional confusion occurs due to the link in the Javadoc description, which basically points to https://docs.unity3d.com/ScriptReference/Quaternion.LookRotation.html. This function creates a "global rotation", as far as I can understand.

So: Should `lookAlong()` work as it does, or is this a bug?

**Comment by httpdigest** [comment]
The method [Quaternionf.lookAlong()](http://joml-ci.github.io/JOML/apidocs/org/joml/Quaternionf.html#lookAlong-org.joml.Vector3fc-org.joml.Vector3fc-) applies (i.e. post-multiplies) a "camera" rotation to make the camera look at a given direction, based on the current frame of reference represented by `this` matrix.

This is what is meant by the Javadoc sentence: "**Apply** a rotation to this quaternion that maps the given direction to the positive Z axis."

And also by: "If Q is this quaternion and R the quaternion representing the specified rotation, then the new quaternion will be Q * R. So when transforming a vector v with the new quaternion by using Q * R * v, the rotation added by this method will be applied first!"

Also, depending on what exactly it is that you want to rotate (either the _camera_ or an _object_ in your scene) you have two opposing frames of references and need to use a different method. When you want to rotate an object in your scene, you need to use [rotationTo()](http://joml-ci.github.io/JOML/apidocs/org/joml/Quaternionf.html#rotationTo-org.joml.Vector3fc-org.joml.Vector3fc-), which does set the matrix to an absolute rotation and does not apply a rotation to the matrix. Sadly, there is no such "set the matrix to a camera rotation" for Quaternionf/Quaterniond currently. Such a method only currently exists on the matrix classes, and is called `setLookAlong()`. I will add it to the quaternion classes as well.

Additionally, please note that `lookAlong` is basically an equivalent to the matrices' `lookAt` methods, which themselves mimic GLU's gluLookAt(); but in the quaternion case without a translation, since a quaternion can only represent rotation (and uniform scaling) but no translation.

So, currently, your best choices are:
* If you want to create an absolute rotation with a quaternion for a camera, use: `quat.identity().lookAlong(...)`
* If you want to apply a relative rotation for a camera, use: `quat.lookAlong(...)`
* If you want to create an absolute rotation for an object in your scene, use: `quat.rotationTo(...)`
* If you want to apply a relative rotation for an object in your scene, use: `quat.rotateTo(...)`
