### ISSUE TITLE
JOML creating a lot of temp files of joml.dll

### ISSUE THREAD

**Issue by AwfulMint** [JOML-CI/JOML#160]
Today I fell my computer too slow so when searching for files to delete I remember the Temp folder in AppData. I see a folder called mintjoml and mintlwjgl and inside mintjoml dozens of folder with strang hash names and inside each one a file called joml.dll, so what hell is going on? '-' 2 hours to delete the mintjoml folder.

**Comment by httpdigest** [comment]
JOML extracts a DLL file contained in the JAR file whenever you are running under Java >= 9 in order to efficiently copy between matrices and direct NIO buffers using the virtual memory address of the buffer.

The hash is computed based on the CRC32 checksum of the byte content of that DLL file. All of this is done by the [SharedLibraryLoader](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/internal/SharedLibraryLoader.java) class.

There have been exactly three different versions of that DLL file, though, so I would expect at most three different folders in the mintjoml (it should have been called 'jomlmint' btw.) folder, not "dozens" of them. I have exactly two such different hash folders in my joml temp folder with one DLL file each.

Please provide the exact version of JOML you are using. And please observe when you'll get two or more of such folders in the future when running JOML in the future.
If you can, probably debug into the SharedLibraryLoader for two successive executions of your program using JOML, to see whether the DLL file will be extracted two times and not one.
