### ISSUE TITLE
The use of Unsafe

### ISSUE THREAD

**Issue by javagl** [JOML-CI/JOML#173]
The `Unsafe` class has been announced to become deprecated for quite a while now. And using it in the latest Java versions causes a warning.

This has already been addressed in https://github.com/JOML-CI/JOML/issues/138 , but I think that the corresponding line here: https://github.com/JOML-CI/JOML/commit/7d1d19616127875122c5ac0faf8adea0e87b01fb#diff-b03b930d7168759913e9d88e5645bd2bR2581 does not cover Java 10 or 11...

To be realistic: The `Unsafe` class will not be removed so quickly. There's too much code out there depending on it. But JOML should not be one of the libraries that use it.

(Rather a side note: I've never seen a reliable benchmark indicating that it is actually *faster* for the kind of operations that it is used for in JOML. I doubt that it brings any advantage *at all*...)

You should consider removing the use of `Unsafe`, or at least make the `joml.nounsafe` option the default (if this does not have other, undesirable side effects).

**Comment by httpdigest** [comment]
Use the latest version of JOML (or at least 1.9.10). The commit you linked to has been superseded by https://github.com/JOML-CI/JOML/commit/48a70f9df94c5af52b157fe49c5f5c9053ba4dc7.
JOML continues to work fine using Unsafe on JDK 9, 10, 11 and the current 12-ea (build 25). There is no issue in using Unsafe, and I will remove it as soon as there is a JDK version out there which truely does not support Unsafe anymore.
Using Unsafe still is benefitial giving a 2x performance increase for writing to a NIO Buffer having a position/offset larger than 0. That scenario is common when filling a UBO with multiple matrices.
So, as long as it doesn't hurt using Unsafe, there is no reason to remove its usage.

**Comment by javagl** [comment]
It's hard to imagine a real performance benefit here. AFAIK many of the `*Buffer`-methods are intrinsics anyhow. Did you do any dedicated benchmark for that? 

However, closing this one, because both sides are unlikely to change in the near future.

**Comment by httpdigest** [comment]
> Did you do any dedicated benchmark for that?

Yes, I did. Extensively. The problem is that HotSpot cannot eliminate bounds checks of absolute Buffer.put()/get() calls when the offsets are not constants. There is even a dedicated branch in MemUtilNIO when the position of the buffer is 0 to use constant offsets for the individual .get() calls, which will be optimized by HotSpot.
See: https://github.com/JOML-CI/JOML/blob/master/src/org/joml/internal/MemUtil.java#L284-L299
That is about twice as fast as: https://github.com/JOML-CI/JOML/blob/master/src/org/joml/internal/MemUtil.java#L302-L317

And yes, HotSpot lowers the get operations to simple MOV x86 instructions, but it will still perform bounds checks for each individual .get() call. This is what slows it down.

**Comment by javagl** [comment]
OK, I just found https://github.com/JOML-CI/joml-bench/blob/master/src/org/joml/bench/MemUtil.java  - maybe I'll have a closer look at that one, thanks.
