### ISSUE TITLE
JOML 1.9.14 lookat up down bug

### ISSUE THREAD

**Issue by ternsip** [JOML-CI/JOML#179]
When I apply lookAt
`new Matrix4f().lookAt(p, t, UP_DIRECTION);`
where 
p = ( 0.000E+0  5.505E+1  0.000E+0) = (0, 55.05, 0)
t = ( 0.000E+0 -5.000E+0  0.000E+0) = (0, -5, 0)
UP_DIRECTION = ( 0.000E+0  1.000E+0  0.000E+0) = (0, 1, 0)
I receive maflormed matrix (� = NaN)
```
� � � �
� � � �
 0.000E+0  1.000E+0  0.000E+0 -5.505E+1
 0.000E+0  0.000E+0  0.000E+0  1.000E+0
```
I'm not sure, but it can be because of unstable dot product (there are stable variants)

**Comment by httpdigest** [comment]
Your view direction (different between target and position) is the same as your up direction. So you are basically giving setLookAt only a single vector (the look direction) and telling it to define an orthonormal basis with that single vector. The cross product of a vector with itself (which is computed inside of setLookAt to compute the "left" direction) is the zero vector and since there are an infinite number of possible solutions (rotations around that look direction), you are effectively getting NaN as a result of a division of 0/0.
An application must catch this singularity case, instead of JOML having to give you an arbitrary solution.

**Comment by ternsip** [comment]
Thank you very much for quick response and explantations. But I still have a question.
My camera looking from 't' to 'p', and I use UP_DIRECTION to get transofmation matrix. 
So in case when I'm looking collinear to third argument what should I do in the program to handle that?

**Comment by httpdigest** [comment]
It sounds like you are trying to define the orientation of an arbitrary object via lookAt. Do not do that, but use Euler angles (via `Matrix4f.rotateXYZ(...)`) or quaternions (class `Quaternionf`) instead. Quaternions can be converted to matrices and vice versa.
