### ISSUE TITLE
The new optimized rotateAxis (v1.9.18) could omit the direction of the axis

### ISSUE THREAD

**Issue by Ealrann** [JOML-CI/JOML#193]
Hello,

After updating to v1.9.18, some rotations are now reversed. I dig a bit, and I think it's due to ed9c2e0 (but it's maybe not the only one, d6a6296 looks similar):
```java
public Vector3d rotateAxis(double angle, double aX, double aY, double aZ, Vector3d dest) {
    if (aY == 0.0 && aZ == 0.0)
        return rotateX(angle, dest);
    else if (aX == 0.0 && aZ == 0.0)
        return rotateY(angle, dest);
    else if (aX == 0.0 && aY == 0.0)
        return rotateZ(angle, dest);
    return rotateAxisInternal(angle, aX, aY, aZ, dest);
```
In my case, **my axis is (0, -1, 0)**. So the old rotateAxis made a reverse rotation (looks ok to me). But, with the new version, JOML use rotateY, but the angle is not reversed anymore.

**Comment by httpdigest** [comment]
Thanks for reporting! You are of course totally right and I totally did not see that coming. Will be fixed in the next [1.9.19-SNAPSHOT build](https://travis-ci.org/JOML-CI/JOML/builds/596685739).
The fixed optimization for Vector3/4 still cuts the runtime in half, so definitely worth it, though. :)

**Comment by httpdigest** [comment]
New release version 1.9.19 with the fix is available at Maven Central.

**Comment by Ealrann** [comment]
Ha, thank you for the really fast fix!
