### ISSUE TITLE
Why not using an float array in Matrix4f?

### ISSUE THREAD

**Issue by neo-expert** [JOML-CI/JOML#195]
The Matrix4f class uses 16 fields to strore the Matrix:
```
float m00, m01, m02, m03;
    float m10, m11, m12, m13;
    float m20, m21, m22, m23;
    float m30, m31, m32, m33;
```
why not using a float array instead? It would be nice, because many opengl methods need the matrix as float[] array.

**Comment by httpdigest** [comment]
The reason is: performance of matrix transformation methods. Those are faster when accessing primitive fields instead of array elements. And actually, as far as native interop is concerned (such as OpenGL), the best there would be a NIO Buffer or simply a long address pointing to off-heap memory. But arithmetic in transformation methods would be even slower then. So, with the primitive field, arithmetic is fast, but we incur the cost of copying the data to off-heap memory for native interop, such as with the various Matrix4f.get(...) methods. So, it depends on the user application what the best strategy would be for storing the float values.

**Comment by XenoAmess** [comment]
That is really an interesting question about wether it worth to choose to use several floats but not a float array.
I made a copy of Matrix2fx who use float array instead of floats.
The test is here : https://travis-ci.org/XenoAmess/JOML/jobs/600134983
You can just search "Matrix2fPerformanceTest" and see using several floats will be more than 30 times faster (for my testcases).
