### ISSUE TITLE
Wonder about the design of relationship between Matrix4fc and Matrix4f

### ISSUE THREAD

**Issue by XenoAmess** [JOML-CI/JOML#196]
There be a lot of functions in Matrix4fc accept(and even return) Matrix4f.
I just cannot understand why we must force user to use one of an implementation of an interface?

What I want to say is that if you really think there should be only one type of Matrix4fc, means Matrix4f and its child-classes, then why you split it into Matrix4fc and Matrix4f? Why we need an interface here, just make a class Matrix4f will make things quite easier isn't it.

And if you think it shall have more types of Matrix4fc that can be implemented by users, imagine such a scenario: (which is what I'm facing now)
Now I want to make a class Matrix4f_xenoamess, it shall implement Matrix4fc, but has completely no relation with Matrix4f.
I want it can be work well with all other Matrix4fc objects.
Then I suddenly find that I must implement function
[public Matrix4f mul(Matrix4fc right, Matrix4f dest);] because this function is in Matrix4fc.

It means if I want a Matrix4f_xenoamess object can multiply a Matrix4fc and save it to a dest, then well this dest MUST be a Matrix4f, but not my Matrix4f_xenoamess class.
And this function in the interface so I must implement it.

I really think it weird, counterintuitive and have risk of low performance. 
IMO the function [public Matrix4f mul(Matrix4fc right, Matrix4f dest);] shall be changed into [public Matrix4fc mul(Matrix4fc right, Matrix4fc dest);]
And if you really care about performance, you can implement [public Matrix4f mul(Matrix4fc right, Matrix4f dest);]  and add another function [public Matrix4f mul(Matrix4fc right, Matrix4f dest);] in Matrix4f, to make them same name functions.

The same problem is about function [Vector4f transform(Vector4f v);] in Matrix4fc. I have no idea why we don't use Vector4fc here.

I want to hear about your opinion. At least give me some suggestions about how shall I make this class Matrix4f_xenoamess in an elegant way.

**Comment by httpdigest** [comment]
Just because there is an interface does not mean it is supposed to be implemented by multiple classes. The "c" suffix interfaces are meant as a read - only view onto a data class. So, Matrix4fc provides only methods that will not modify `this`. When you use Matrix4fc in your code, you express the intent of never modifying it through this variable. It can be modified through an alias variable with the type of the implementation class, though.
See: 
- https://github.com/JOML-CI/JOML/issues/52
- https://github.com/JOML-CI/JOML/issues/134

As for extending the classes in JOML: they are not designed for extensibility and I don't see a reason why one would want to extend them. If there is a feature missing, simply make a pull request or open an issue.

**Comment by XenoAmess** [comment]
I guess I understand what you mean now. 
I will try to code out what I think better design and do some performance test to see if it really can do.

**Comment by httpdigest** [comment]
Please don't. You should spend your time elsewhere. It's very unlikely that this design will change, unless you have some very good reasons with actual real world use cases.
