### ISSUE TITLE
SIMD integration with YEPPP java simd library

### ISSUE THREAD

**Issue by jduke32** [JOML-CI/JOML#29]
hello , i have seen yeppp simd library that is very fast and makes AVX , AVX2 instructions move to java with it easily.
http://www.yeppp.info
it has JNI bindings also.
Thanks.

**Comment by httpdigest** [comment]
Thanks for proposing Yeppp! I did not know about that, yet.
I will benchmark it, however I have doubts about the usefulness of a non-native language binding (such as Java) and its usefulness for JOML.
Yeppp! itself will surely be great for native applications, no doubt about that! :)
But I had a look at Yeppp!'s API and they provide very very low-level SIMD instructions as JNI methods.
This is likely to be many orders of magnitudes slower than even the corresponding Java scalar code, because of tremendous JNI overhead.
Java scalar floating point arithmetics code will be converted to x86 SSE scalar arithmetics instructions and do not suffer from any method/JNI overhead.
Yeppp! now has the overhead of a JNI function call itself, but then they also suffer from their representation of SIMD vector types, which is float[] arrays, which is bound to use GetFloatArrayElements/ReleaseFloatArrayElements JNI functions to reliably access those float arrays, so they must call repeatedly into the JVM for every single SIMD instruction.
Even the cost for a single native function invocation will outweigh the gains of a SIMD instruction by some orders of magnitudes.
But I will test it!
What I wish for, though, would be class provided by the Java Runtime Environment so that the JVM knows to convert those methods into SSE intrinsics when JIT'ting the JVM bytecode into x86. :)
But again, thanks for mentioning it. I will test it.

**Comment by httpdigest** [comment]
Okay, here are the numbers:
Yeppp!'s Java binding is about 104 times slower than corresponding scalar Java code working on float[] arrays, and about 110x slower than JOML using Vector4f.add invocations working on the primitive float x, y, z, w fields!
The functions that Yeppp! provides are just too primitive, meaning that they do not do a lot of work.

**Comment by httpdigest** [comment]
Just one thought I had recently:
What "could" be done however to increase the "arithmetic density" and therefore hide the latency of JNI, is to use the Matrix4f as some sort of "builder". Invoking Matrix4f methods are lazily "journaled" internally as long as one does not need any intermediate result (terminal operation) of the matrix operations (with Matrix4f.get(FloatBuffer) being such a "terminal operation) and then eventually [http://blog.reverberate.org/2012/12/hello-jit-world-joy-of-simple-jits.html](JIT-generate SSE code) with a small support library.
A "chain" of Matrix4f method invocations like perspective().lookAt().rotate().mul(matrix).invert().get(fb) would then be translated to a single JIT'ted native function.
Now the only problem we have is: How do we get the actual arguments of the various Matrix4f methods to be accessible by JNI.
An actual access of the 16 float fields would likely be very slow. There could be the possibility of accumulating float arguments into a direct ByteBuffer and then JIT code that accesses the correct offset into that ByteBuffer.
That "could" at some break-even point be faster than Java code, if just enough arithmetics are involved in it.

**Comment by jduke32** [comment]
so to utilize yeppp , we need to send bulk matrix data , not single 4x4 matrix , right?

**Comment by jduke32** [comment]
for 1024x1024 matrix operations ? yeppp also bad ?

**Comment by httpdigest** [comment]
Have a look at https://github.com/JOML-CI/JOML/issues/30. There I outlined what needs to be done to make at least use of native SSE code for JOML.

**Comment by jduke32** [comment]
there can be automatically benchmark at pc runtime and choose which method to choose.
JNI or JIT.

public static void initMatrixStage(int columnPreffered[],int rowPreffered[],boolean bulksendOperation) {
     //benchmark jit and get time consumption 
    //benchmark yeppp jni solution
    //benchmark for AMD APARAPI solution
    //choose at init stage.
}

**Comment by jduke32** [comment]
Do you know AMD APARAPI ?
http://developer.amd.com/tools-and-sdks/opencl-zone/aparapi/

**Comment by gouessej** [comment]
@jduke32 Using a Java binding for the OpenCL API like JogAmp JOCL would give a lot more flexibility than Aparapi.

**Comment by httpdigest** [comment]
Closed because YEPPP! is not relevant for JOML.
