### ISSUE TITLE
rotation matrix scaling

### ISSUE THREAD

**Issue by TheoW03** [JOML-CI/JOML#338]
I dont know if this is a code or a math issue, but when I use a rotation matrix like this

```JAVA
        Matrix4f m = new Matrix4f();
        m.identity();
        m.rotate(45,1,0,1);
 ```
it scales my render
![image](https://github.com/JOML-CI/JOML/assets/95878514/fc6a5e00-03fc-4902-bde5-1a4f1962b497)

```GLSL
   vec4 l = rot*vec4(position, 1.0);
    gl_Position = l;
```
(this is the shader code for it because I am sending it to the GPU, rot is the Rotation matrix "m" in my java code)

I so far been only able to reproduce the bug when I do combinations of rotation angles.

**Comment by httpdigest** [comment]
The axis must be a (normalize) unit vector, as mentioned by the JavaDoc of this method: https://javadoc.io/doc/org.joml/joml/latest/org/joml/Matrix4f.html
> The axis described by the three components needs to be a unit vector.

This is in order to save one additional Math.sqrt() and division which would otherwise be necessary in order to normalize the axis. So, in this case, the caller must ensure that the axis is normalized.
