### ISSUE TITLE
There is a bug

### ISSUE THREAD

**Issue by BitYorkie** [JOML-CI/JOML#34]
Math.cos(Math.toRadians(90)) != 0 ;
I can't write in English.Also can't github...o(╯□╰)o

**Comment by sriharshachilakapati** [comment]
The `Math` class does not belong to JOML library, I can't see what you are trying to say.

**Comment by BitYorkie** [comment]
class Matrix4f  
	public Matrix4f rotation(float angle, float x, float y, float z) {
		float cos = (float) Math.cos(Math.toRadians(angle));
		float sin = (float) Math.sin(Math.toRadians(angle));
		float C = 1.0f - cos;
		m00 = cos + x * x * C;
		m10 = x * y * C - z * sin;
angle = 90 , cos err

**Comment by httpdigest** [comment]
Please use more prose to express your problem. "There is a bug" and posting snippets of deprecated methods is not a good problem statement. Note that as of 1.3.5-SNAPSHOT JOML does not use degrees anymore for angle parameters but radians instead.
If you can't write in English, then maybe express your problem in your native language properly so that I can at least run that through Google Translate. :)
Also note that `(float) Math.cos(Math.toRadians(90))` will not give you `0.0` because of lost precision when converting degrees to radians (PI cannot be exactly represented and Math.cos also has inaccuracies). I am getting `6.123234E-17` as result, which is pretty close to `0.0`.

**Comment by BitYorkie** [comment]
谢谢你的耐心解答 O(∩_∩)O~
我很抱歉影响你的时间是我自己的错误,真是无地自容

我非常非常喜欢你们的代码 在这里再次谢谢你

**Comment by sriharshachilakapati** [comment]
After translating that with Google Translate:

> Thank you for your patience to answer O (∩_∩) O ~
> I'm sorry affect your time is my own mistakes, really shame
> 
> I very much like your code here thank you again
