### ISSUE TITLE
There's no way to convert Vector* classes to a FloatBuffer

### ISSUE THREAD

**Issue by pateman** [JOML-CI/JOML#39]
It's an improvement request, actually. Maybe you could add the very same get() method as Matrix4f to all Vector classes?

**Comment by httpdigest** [comment]
You may have to update your local clone repository. All vector classes have ByteBuffer and FloatBuffer get/set methods contributed by @ra4king with https://github.com/JOML-CI/JOML/pull/37.
See this merge: https://github.com/JOML-CI/JOML/pull/37#event-365949205

**Comment by pateman** [comment]
Ah, I downloaded the 1.3.5-SNAPSHOT release... Sorry, this can be closed.

**Comment by httpdigest** [comment]
Ah, okay. I think I will discontinue the GitHub Releases, since now real releases are being deployed to Maven Central and Snapshot releases to oss.sonatype.org.
So, either git clone this repository and build yourself, or use Maven/Ivy/Gradle for dependency management with the snapshot repository `https://oss.sonatype.org/content/repositories/snapshots` for snapshots, or manually download the jar from this repository or Maven Central (for major releases).

**Comment by pateman** [comment]
Yeah, that sounds much better. I git cloned the repo and ran Maven. Thanks a lot and sorry for causing ruckus! :)

**Comment by httpdigest** [comment]
You're welcome. No problem! :)
