### ISSUE TITLE
Have all get*(...) methods return the object that is being set

### ISSUE THREAD

**Issue by ra4king** [JOML-CI/JOML#43]
For example Matrix4f.get(ByteBuffer) should return ByteBuffer, not Matrix4f.
I can implement this if a consensus is reached :+1: 

A good argument for this is that it compresses 3 lines of code into 1, as well as eliminate the need for a named local variable. From this:

    ByteBuffer buffer = getBufferMagically()
    myMatrix.get(buffer);
    glUniformMatrix4fv(myMatrixUniform, false, buffer);

Into this:

    glUniformMatrix4fv(myMatrixUniform, false, myMatrix.get(getBufferMagically()));

This way, what is happening here is easy to understand in 1 line as all I need to see is everything up to `myMatrix`, ignoring everything after and including the `.get`. Thus I can see that myMatrix is being set at the value of myMatrixUniform.

**Comment by httpdigest** [comment]
Oh, this is a really nice proposal! I'd like to do it this way, but yes, we should wait a bit for other users to reach a consensus.
Another thing that we could also change is something I observed myself doing lately:
Have all methods with a 'dest' parameter return that 'dest' parameter instead of 'this'.
See [this line](https://github.com/JOML-CI/joml-lwjgl3-demos/blob/master/src/org/joml/lwjgl/ProjectiveShadowDemo.java#L200) of a demo program for example.

**Comment by ra4king** [comment]
Yes in general, I think the rule should be to always return the object that is modified.

**Comment by httpdigest** [comment]
Yes, that would be a nice rule, which is easy to comprehend.

**Comment by ra4king** [comment]
Since you agree, I will begin the quick work for the pull request in hopes of reaching consensus. It will be some fun regex :smile:

**Comment by httpdigest** [comment]
Good luck catching all JavaDocs ;)
But in the context of this issue, please first only prepare the `get` methods only.
Additionally, later we can prepare a separete issue and PR with all methods returning `dest`.

**Comment by ra4king** [comment]
I am including all methods that begin with `get`. For the Matrix classes, this includes getColumn, getRow, and getTransposed

**Comment by tkausl** [comment]
I thought about opening an issue for something similar, math-operations with a dest-value should return the dest-object in my opinion:
```
Matrix4f another = new Matrix4f();
matrixA.mul(matrixB, another);
```
vs
```
Matrix4f another = matrixA.mul(matrixB, new Matrix4f();
```

Also, i don't see *any* reason why you would need the original matrix, not the modified destination-matrix for further operations (chaining).

**Comment by ShadowLordAlpha** [comment]
I see no problem with the two suggestions though it would break backwards comparability for anyone relying on the return value or the methods for whatever reason.

**Comment by ra4king** [comment]
Yes it would definitely break backwards compatibility but as far as I know, this library is still in development and hasn't been declared final yet. Also, I believe this feature is critical as it is the most intuitive way of using it so I fear some that are unaware are chaining thinking they are modifying the destination rather than the source.

**Comment by httpdigest** [comment]
What people always think about the lifecycle of a framework... :-)
A library like JOML will never be "finished" in the same sense that no application or framework will ever be finished. JOML lives and thrives from people actually using it and giving 'use cases,' which I am always happy to support with JOML. There are of course opposing forces here:
- on the one hand, people will want to wait for a framework to become stable before deciding to use it, because once integrated, whenever the framework changes in API, the application needs to adapt to those changes too, and this is work
- on the other hand, a framework can only become stable if people are using it and are living with the fact that they themselves help in improving the library by using it, giving feedback and providing 'use cases'

Both forces depend on each other. Strictly speaking, JOML has been "finished" and could be "used" since version 1.0.0, albeit of course at that point in time there was not many existing use cases and functionality in JOML to support such use cases. But JOML could not be said to have been "incomplete" then, because JOML is trying to aim a moving target and therefore the definition of "complete" is different.
A bit provocatively speaking, what people usually mean when they say "finished" in the context of a framework like JOML, is: "dead"
But that was a bit too harsh maybe. "Finished" would mean, that there are no new use cases that need to be supported by JOML and that people using JOML currently are content with it.

**Comment by ra4king** [comment]
Cool, with your most recent commits, I believe this issue is closed. Excellent!

**Comment by httpdigest** [comment]
Alright. I think I am going to push out the 1.5.0 release, then, which will make everything done so far available on Maven Central.
And with the added functionality and changed semantics, it feels like "1.5.0" is the right version name (or rather just "5" :) )...
