### ISSUE TITLE
Change Non-Static methods to Static

### ISSUE THREAD

**Issue by ShadowLordAlpha** [JOML-CI/JOML#50]
There are a number of methods inside JOML that could be changed into static methods without any real change in functionality other than needing to reference a class instead of an object to get to the method. For example 

```java
 public Vector3d sub(Vector3d v, Vector3d dest) {
        dest.x = x - v.x;
        dest.y = y - v.y;
        dest.z = z - v.z;
        return dest;
    }
```

could very easily be 

```java
 public static Vector3d sub(Vector3d v, Vector3d dest) {
        dest.x = x - v.x;
        dest.y = y - v.y;
        dest.z = z - v.z;
        return dest;
    }
```

with no loss of functionality and should reduce the overall size of the object by changing it from one copy of the method per instance to one total.

**Comment by ra4king** [comment]
This doesn't make any sense. The one you showed is an instance method that operates on instance variables.

**Comment by ShadowLordAlpha** [comment]
I know i just remembered that and closed it because of that

**Comment by httpdigest** [comment]
This issue has been closed, but let me comment on it for possible future issues:

> ... without any real change in functionality other than needing to reference a class instead of an object to get to the method. 

Instead of arguing that a change would not make things *worse* (other than of course requiring a huge amount of work to implement it), the arguing on your side has to be the other way around: "What **gain** do we get from that? What would **improve**? How will someone **benefit** from it?"

> ... and should reduce the overall size of the object by changing it from one copy of the method per instance to one total.

No. Absolutely not.
Instance methods are not "copied" per instance/object. No matter what kind of method, all methods only exist one single time in memory associated to the class they are declared in. And even dynamic dispatch (Google for "Dynamic Dispatch"), which is to find the correct method to call based on the runtime type of the object and the inheritance hierarchy of its class, is guaranteed to be inline-cached (Google for "Inline Caching") by modern JVMs and most of the time even completely inlined to the callsite, so those methods are by no means slower to invoke than static methods.
