### ISSUE TITLE
Add interfaces to all public api

### ISSUE THREAD

**Issue by empirephoenix** [JOML-CI/JOML#51]
would it be possible to add to all data classes an interface?
eg interface for Vector3f ect.

a) own extended implementations (eg one combining the interface of javax.vecmath, jme3.math and joml without having to copy stuff all over between different used librarys)
b) make migration way easyer, as the public interface could stay the same as before, just the internals are changed to joml.
c) allow clean use in persistence contexts, as java.util proxys are possible without bytecode modifications

**Comment by httpdigest** [comment]
It certainly would be possible. However currently I really do not see any necessity for polymorphism in JOML.
Also note that neither javax.vecmath nor JME provide Java interfaces for their APIs.
So you would have to ask them, too.
And I also do not see why one would want to combine all those vecmath libraries into one.
If you need functionality in JOML that you are currently missing, please ask for it or provide a Pull Request.
I do however see the possiblity of wanting to decouple one's application from JOML in order to easily switch to another vecmath library, should one choose so.
In this case, it is better for an application or another third-party library to provide the API in the form of Java interfaces, which the application then provides implementations that use delegation over inheritance to adapt to JOML and other vecmath libraries. (that would cover your point b) I guess).
However, also note that the API (i.e. "contract") of a framework is not just merely the method signatures but the semantics of those too.
You have to think about things such as multithreading, changing application state, throwing exceptions in which cases, possibly interacting with I/O, such as logging. Those are all part of the "API."
In order to use JOML in a persistence context, such as JPA if I get you right, to store matrices and vectors in databases or sorts, is what cglib handles in the Java EE application containers.

**Comment by tterrag1098** [comment]
I'd like to resurrect this issue, by describing a use case I'd have for such an interface.

The interface I'm imagining would look something like this:

```java
public interface Vector<T> {
  
  int getSize();

  Class<?> getType(); // This would return something like Float.TYPE

  // Then some non-type dependant methods

  FloatBuffer get(FloatBuffer buffer);

  FloatBuffer set(FloatBuffer buffer);

 // etc etc ...
```

My use case is that I'm writing some utils to convert collections of vectors into NIO buffers, and it's proving quite tricky to do without a common supertype for all vectors. Since I can't have different methods that take Collection<Vector*f>, as they all erase to the same signature.

So I'm asking that you please consider better polymorphism in this library.

If my reasoning is flawed, or there's a better way to do what I'm trying to do, please, let me know.

**Comment by httpdigest** [comment]
Could you probably elaborate more on your use-case? As I understand, you want to treat all vectors in a collection alike by using a polymorphic method that you can invoke on all vectors.
What is the concrete reason you want to have such a polymorphic (in the sense of the type argument of the collection) utility method to write vectors into a collection? Is it to build an OpenGL (vertex/shader storage) buffer object with a stream of structures composed of different vector-size members?
In that case I'd recommend not using vector objects in the first place or providing overloaded utility methods working directly on a concrete vector type.
If you don't want to overload, then a simple `instanceof` test will also do just fine.

**Comment by tterrag1098** [comment]
I guess I just don't see why you wouldn't implement a polymorphic supertype for vectors, since all of the vector classes have some methods which have identical signatures. It doesn't seem like it has a downside, at least to me. It won't break past API and it makes dealing with the objects easier.

In my specific case, I am "porting" (more like rewriting) some C++ OpenGL code in which I had a list of vector objects, and due to the nature of the language, I could just upload that list directly. So I'm looking for some analog to that, in the form of converting to NIO buffers.

**Comment by httpdigest** [comment]
It's not that I woudn't implement polymorphic supertypes. It's that I always like to weigh the pros and cons for everything added to the library/API, and only add it when really needed/asked for, since everything added is an increase in complexity. And currently I like that JOML is actually pretty simple (there are very few 'conceptual' things in it).
But now that you made it clear what your use case is, I'll add a `Vector` interface implementing the necessary get(Buffer) methods. For now, they are going to reside in a `vector-interface` branch.

**Comment by tterrag1098** [comment]
Thanks! However, that interface will fall short because buffers have to be preallocated, and there is no way to determine the size of a Vector object. It could still be useful in other cases, but not mine specifically.

Still, it seems like a very useful addition.

**Comment by empirephoenix** [comment]
To be honest, I kinda not seee this problem anymore :)

Even tho I initially created this issue, having a supertype in the core is really not useful at all. 

My suggestion is, fork the github, and modify it for a own build, because like this there are dozens of similar smaller changes that are only required for a very limited amount of projects.

**Comment by tterrag1098** [comment]
@empirephoenix I may very well do that, but I figured it was worth adding my 2c, and it seems it has helped in at least some way.

**Comment by httpdigest** [comment]
> and there is no way to determine the size of a Vector object

Yeah, sorry. Forgot about that. Commit https://github.com/JOML-CI/JOML/commit/d3084b64491325c89188bbd6661dca887c061143 should have everything you need.
