### ISSUE TITLE
Add fma to Quaternion classes

### ISSUE THREAD

**Issue by bardackx** [JOML-CI/JOML#57]
Given that a Quaternion is used to represent orientations (...) and a Vector3 is used to represent rotations, can we have a method to add scaled rotations to a quaternion? —like the fma of vectors, by the way, what fma stands for, what does it mean?

	// current way to add a rotation to a orientation
	private static final void addRotationToOrientation(final Quaternionf orientation, final Vector3f rotation, final float dt) {
		Quaternionf q = new Quaternionf(rotation.x * dt, rotation.y * dt, rotation.z * dt, 0);
		q.mul(orientation);
		orientation.w += q.w * 0.5f;
		orientation.x += q.x * 0.5f;
		orientation.y += q.y * 0.5f;
		orientation.z += q.z * 0.5f;
	}

	// desired way
	orientation.fma(dt, rotation);

**Comment by httpdigest** [comment]
The word fma is an abbreviation for "fused multiply-add". It was added to some processor instruction sets to perform multiplication and addition in one step with high accuracy without rounding. Even though "fma" in JOML does not necessarily perform these two arithmetic operations without rounding, the name "fma" was chosen nonetheless because it is quite common and because of the same sequence of arithmetic operations.
A vector does not represent a rotation. It merely represents the axis around which to rotate. A quaternion is both the axis of rotation as well as the amount (the angle) of rotation.
What you probably need is simply Quaternion.mul to concatenate two rotations represented by two quaternions.
Maybe you can explain more what exactly you need and what your use case is.

**Comment by bardackx** [comment]
In the book Game Physics Engine Development that's how they add a vector representing a rotation (in radias per second) to an quaternion representing an orientation orientation.

This is an excerpt from he chapter 9.3 Angular Velocity and Acceleration fro that book

![2](https://cloud.githubusercontent.com/assets/234251/9748861/8b1a091c-564d-11e5-8737-c8652923c7f8.PNG)

And this is part of the Mathematics Summary : C.2 Quaternions

![1](https://cloud.githubusercontent.com/assets/234251/9748862/8b1d6418-564d-11e5-9a52-945951329b98.PNG)

**Comment by httpdigest** [comment]
Okay, the vector you were talking about was the angles with respect to the three base axes (x, y, z) around which to rotate, and each component of that vector gave the amount of rotation around that respective axis. This is called "Euler Angles."
There is a [thread at math.stackexchange.com](http://math.stackexchange.com/questions/261193/updating-a-quaternion-orientation-by-a-vector-of-euler-angles) talking about the same thing, I guess.
So the concrete use case you might have had in mind, and also what those books are referring to, is integration. You would like to have the possibility to integrate a rotation over time differentials to come up with a new rotation/orientation each "frame."
Can you please tell me whether this is your use case and this is what you want/need?

**Comment by bardackx** [comment]
That is the case; I want to integrate rotation (that's how they define angular velocity in the book, it can be misleading) into orientation over time.

Although in the book they not explain the mathematical fundation of that, but it works.

**Comment by httpdigest** [comment]
Hi @bardackx, I finally added your request to JOML's Quaternion classes with https://github.com/JOML-CI/JOML/commit/89263bd86767bf157faa3f984b7c1ae6c5c7f6ee.
Thanks for suggesting! It is indeed very useful for physics and also for implementing a camera rotation.
