### ISSUE TITLE
Shorter naming scheme?

### ISSUE THREAD

**Issue by dustContributor** [JOML-CI/JOML#61]
Hi! First and foremost, its great work what y'all are doing here :smile: 

To the point, have you considered shorter naming scheme for all types?

Things like

- Vec3d instead of Vector3d
- Mat4f instead of Matrix4f
- Quatf instead of Quaternionf

And so on... What do you think? Its a bit closer to what you see in GLSL :smile:

**Comment by httpdigest** [comment]
No, I never thought about using shorter names. I guess I'm more the typical Java-programmer, writing all-and-everything out, instead of the C/GLSL programmer abbreviating where they possibly can. ;)

Like with every change, we can do the "cost" vs. "benefit" comparison here.
Costs:
- will break every client and tutorial/book out there so far using JOML
Benefits:
- will make type names look more like GLSL (probably with Dvec3 instead of Vec3d, although that looks ugly) ;)

It sure would be nice to let JOML code resemble equivalent GLSL code more, but due to the lack of overloading operators in Java, this is not possible to the degree where that would be practical.
So, JOML rather chose to resemble the type names of other established vecmath libraries, such as Java 3D's javax.vecmath.

**Comment by dustContributor** [comment]
javax.vecmath is considered established? Dang :P

> will break every client and tutorial/book out there so far using JOML

Eh, the situation will get worse over the time. If thats going to be a criteria and if anyone would want to make the change, I'd say that  its right now or never. Lib is still pretty young, so I dont think its that big of a deal.

Buuut okay, no problem, I guess I can always clone the repo and refactor-rename. Reopen if you ever change your mind! :smiley:
