### ISSUE TITLE
No Matrix4f.get(float[]) overload with zero offset by default.

### ISSUE THREAD

**Issue by dustContributor** [JOML-CI/JOML#64]
Hi! It seems that Matrix4f doesn't has an overloaded .get(float[]) method with default offset 0 like some other set/get methods.

**Comment by httpdigest** [comment]
Thanks for the info! Added with https://github.com/JOML-CI/JOML/commit/194f19cf3768b2a1b7660497b9198b7a6b768506

**Comment by dustContributor** [comment]
Oh I was expecting something like

```java
public float[] get(float[] arr) {
  return get(arr, 0);
}
```

But that works as well, thanks! Should I close the issue?

**Comment by httpdigest** [comment]
I am very conservative when it comes to "inlining." :)
Certain JVMs (for example JamVM) do not fully support inlining all opcodes, determined by the machine architecture the JVM runs on. So delegating to the other `get` method could potentially decrease performance slightly.
Of course on HotSpot this is not a problem.
And code-duplication is also not a problem here, since the probability of that method ever needing to change is about zero. :)
Yes, you can close it, if the changes suit you.

**Comment by dustContributor** [comment]
Okay then!
