### ISSUE TITLE
Geometry primitives

### ISSUE THREAD

**Issue by dustContributor** [JOML-CI/JOML#73]
Hi!

I spent a bunch of time googling around for geometry libs for Java. You know, things with intersection and containment tests between a bunch of geometric primitives (squares, triangles, circles, etc).

Most of them suffer of excessive object orientation (ie, Triangle class of three Point objects, that kind of thing), use all doubles for their computations (excessive for games), non permissive licences (GPL and company), and so on.

These things are the basis of spatial structures, and are also kinda hard to implement under the OOP umbrella since it is a combinatory explosion of optimized methods between specific types (ie, circle contains square isn't the same test as square contains circle, intersection tests are specialized between kinds of shapes, etc).

Ideally there should be a couple of primitives supported:

2D
- Triangle
- Rectangle
- Circle

3D
- Frustum
- Axis aligned box
- Sphere

With operations like shape.contains(otherShape) and shape.intersects(otherShape).

With these all normal spatial structures should be possible I believe. Octree of axis aligned box, sphere tree, frustum culling, etc.

I can contribute a bunch of the 2D implementations, but honestly math isn't my forté.

**Comment by httpdigest** [comment]
Sure, your proposal sounds good!
There should be good resources (math articles/papers) on the internet on how to do all kinds of intersection tests efficiently.
Some intersection tests are already in JOML, specifically for frustum culling: Frustum/Point, Frustum/Sphere, Frustum/AAB. See [FrustumCuller](https://github.com/JOML-CI/JOML/blob/master/src/org/joml/FrustumCuller.java).
I'd encourage you to provide a pull request. Based on that we can then discuss how it will fit into JOML's existing design.

I would also like to avoid introducing classes for geometric primitives (a sphere can be modeled by a `Vector3f` center and a float radius) and using polymorphism via inheritance like you proposed with the `contains` method, because when it comes to that people usually have their own ideas about how to dispatch intersection tests between two different geometric primitives and what should constitute those geometric classes.
JOML should provide the least common denominator by preferably having static methods `thisIntersectsThat(This a, That b)`. Currently, I see an `Intersection` class with all sorts of methods for intersection tests.
Of course, if efficiently requires state/caching (like what the FrustumCuller already does) for two specific geometric types, then an additional class might be needed. But, we'll see.

**Comment by seanrowens** [comment]
I'd like to help with this.  I've been toying with the idea of trying to
write up a library for the low level operations, but as dustContributor
said, math is hard.  There's tons of information out there but a lot of it
is quite opaque.

I also of wish there was some canonical set of low level primitives, i.e.
sphere, triangle, polygon, etc, that any such library could just use and
that I could use myself without having to reinvent the wheel every time I
turn around.  There are of course also issues of efficiency in terms of
memory and speed of course.  The most efficient representations are
probably just arrays or buffers of floats or doubles.  But in my imaginary
library I think I'd use objects to make what is going on easy to follow.
Or maybe have the actual methods take just doubles as parameters, and trust
the JVM to optimize that.

By the way, from what I recollect (I wish I could find a reference for
this, took a quick look but didn't find it) Java promotes everything to
double when doing math so you're not any faster using floats.  C does the
same thing.   If you're doing math on the GPU it's probably worth using
floats for speed.  Otherwise you're just saving memory, which may also have
an effect on the cache but otherwise isn't any fast.

Anyway, I'd like to help.


Sean Owens

**Comment by dustContributor** [comment]
> Java promotes everything to
double when doing math so you're not any faster using floats.  C does the
same thing. 

No, from what I know, it doesn't works like that: You got two ways to do FP in the CPU: x87 and SSE/AVX. 

x87 uses internally 80 bit registers, so CPU pops in the value, computes in 80 bit, then truncates the result to whatever type it was using. This is the slower and older way (*much* older, from the time when FP was done in separate chips because the 8086 didn't supported it), as far as I've seen HotSpot simply won't issue x87 FP code (maaaaybe with the "strictfp" keyword now that I think of it, haven't ever seen it used). 

SSE can do actual 32 bit FP or 64 bit FP. HotSpot can vectorize *very* simple operations (ie, add two float arrays, multiply two float arrays, that kind of thing) otherwise uses non-vectorized forms of SSE, or more specifically, non vectorized forms of whatever ISA your CPU supports (SSE2/3/4, AVX, etc), so it has more registers at hand if the CPU supports it.

Loading 64 bit float has higher latency and its worse for the cache. If it HotSpot ever starts to auto-vectorize things, you don't want to use 64 bit just because, won't vectorize as well as 32 bit. 

Arrays of floats aren't as efficient as plain objects with float fields because the VM will inject length checks on access, whereas with plain objects access is "known" and at most you can expect the standard null check.

Of course, if you're really, really optimizing things, you will be using a plain float[] containing all the data of your shapes (cache benefits would outweigh everything). But so you'd do with all your Vec3f/Mat4f objects if you were going along that road. Not exactly the thing JOML is prepared for as far as I'm seeing, unless you propose of getting rid of Vector3f, Matrix3f and friends too. 

> a sphere can be modeled by a Vector3f center and a float radius

It can but if you do so, you'd be forcing users to store their shapes in tons of tiny objects. Two vec3 for boxes, three vec2 for triangles, and so on. I think a sphere is the only case where you'd have the same level of overhead/indirection if you modeled it with a Sphere object, rest of them you'll be forcing people to use tons of tiny objects. That's more indirection and a waste of memory, you'd be having more object headers around than actual usable data.

In any case, you can provide static methods with plain float parameters for all of these operations, which gives the liberty for the user to do whatever he/she wants as long as they're there.

**Comment by seanrowens** [comment]
OK, I could well be wrong (or out of date) on that float vs double thing.

And yeah, that's what I was talking about re: arrays, keeping everything in
arrays, i.e. array of a bunch of floats where triangle t is stored at n,
n+1, n+2, triangle t+1 is at n+3,  etc.

The static methods with plain float parameters is a good approach, I think,
perhaps with wrapper methods on various Triangle/etc classes.  I.e. class
Triangle has a method "intersect" that calls the static method with fields
from inside Triangle.  If you really want the speed and/or want to use
arrays or buffers you can call them directly.   Does this make sense?  We
should really try to benchmark these things to see if one approach is
really faster than another.

Very interesting info on the lower level stuff, by the way, thanks.

Sean

**Comment by dustContributor** [comment]
No problem. Made the pull request btw #74 

The way I handled the "multiple dispatch" might not be the best, and it only works on Java 8. Still its quite easy to extend if a new shape pops up imho.

**Comment by httpdigest** [comment]
Update: See https://github.com/JOML-CI/JOML/pull/74#issuecomment-173524575

**Comment by httpdigest** [comment]
Please verify if the current Intersection classes contain everything needed.

**Comment by dustContributor** [comment]
Looks like between the intersect methods and the frustum culler there is enough to work out what I had in mind (quadtree, culling for shadowmaps, etc). Most of the stuff is either spheres/boxes or can be approximated with spheres or boxes.

Mmm... Maybe expand the frustum operations? As they stand, the operations say if a volume intersects with the frustum (in the docs referred as "inside or partly inside of the frustum"), but a common optimization on a spatial structure is to check if the volume is completely inside the frustum, since if it is, there is no need to check the subnodes of the volume.

Everything else looks good by me, really nice work :smile: Not sure if anyone else needed something more specific...

**Comment by httpdigest** [comment]
Ah, yes. I'll add to the frustum culler that it can determine whether a sphere or axis-aligned box is completely inside of the frustum.

**Comment by httpdigest** [comment]
Testing whether fully inside or just intersecting is in now with https://github.com/JOML-CI/JOML/commit/1656212db18584156c68a1afa81992a7cd12974a. Please see the commit log and the tests inside of FrustumCullerTest.

**Comment by dustContributor** [comment]
Nice! 

If you want to close this issue go ahead, I guess from now on there will be specific requests/bugs instead of general features like originally this issue was asking for.

**Comment by httpdigest** [comment]
I have been proactively adding other intersection tests in the past days. Maybe you'll find them useful as well.
Especially the line-segment / sphere and line-segment / triangle methods are great for implementing collision detection between meshes and projectiles in some "shooter" game; or just some game where things fly around very fast. :)

**Comment by dustContributor** [comment]
Sweet, I personally use Bullet for that kind of thing (I mean, when I get there, for now I just use it to avoid falling to the void) but there are a lot of people who like to make that stuff on their own :smile:

**Comment by kappaOne** [comment]
really nice work, just curious, any planes to extend JOML a bit more to also include simple polygon shapes (convex and concave)?

**Comment by httpdigest** [comment]
One thing that is definitely going to come soon is polygon triangulation. Just have to do a lot of research what is considered the best algorithm here.
After that, I think I'll reduce "polygon vs. something" intersection tests (at least boolean) to "triangle vs. something" intersections. With this approach, we could also make use of spatial acceleration structures to query only the potentially intersecting triangles.
But again: Need a lot of research before knowing what would work best. :)
