### ISSUE TITLE
Java 9 SIMD and GPU support

### ISSUE THREAD

**Issue by jduke32** [JOML-CI/JOML#77]
Hello , I have looked your source codes.
They are using old technique for Java.
You can add SIMD native java 9.
Java 9 has IntStream that uses simd

IntStream.iterate(17, i -> i % 2 == 1 ? 3 * i + 1 : i / 2)
        .takeWhile(i -> i > 1)
        .forEach(System.out::println);

  1 public static void testForEach() {
  2          
  3     // Vector addition 
  4          
  5     int[] a = new int[SIZE]; 
  6     int[] b = new int[SIZE]; 
  7     int[] c = new int[SIZE]; 
  8          
  9     Arrays.fill(a, 10); 
 10     Arrays.fill(b, 20); 
 11                 
 12     IntStream.range(0, a.length) 
 13              .parallel() 
 14              .forEach( id -> c[id] = a[id] + b[id]); 
 15          
 16     long end = System.nanoTime(); 
 17          
 18     System.out.println(Arrays.toString(c));     
 19 }

http://snatverk.blogspot.com.tr/2014/05/java-streams-in-jdk8-examples.html

**Comment by httpdigest** [comment]
I know about Java 8's Stream API, and I know that streams can be run in parallel on subsequences of its elements.
However, this is very likely not something which JOML will benefit from.
There is currently no usecase for JOML which needs to add like a million vectors together to probably benefit from. JOML is about 3D math.
Apart from that, concurrency and multithreading can be easily done by the client. Simply put one million vectors in a Java 8 stream and add those together at the client. No need for JOML to lower that down to int/float components and add a huge complexity to the library.
But I still very much doubt that this will give a significant gain in performance (also for which usecase?), since memory accesses are the major performance killer. But if you show me a relevant usecase with timings that does benefit from this, I'll think about it.
Also, JOML does not target Java versions (Java 9), which are not even released.
