### ISSUE TITLE
Difference between artifacts

### ISSUE THREAD

**Issue by Guichaguri** [JOML-CI/JOML#88]
I noticed several artifacts from [Sonatype](https://oss.sonatype.org/#nexus-search;quick~joml), and I didn't find any information about them

What is the difference between joml, joml-2d, joml-mini, joml-fastmath, joml-geometry and joml-camera?

Thanks

**Comment by httpdigest** [comment]
joml refers to the master branch. joml-2d, joml-mini, joml-fastmath and joml-geometry refer to the branch named like this, respectively. joml-camera refers to the JOML-CI/joml-camera repository.
You likely want to use joml. joml-mini was an experiment to provide a stripped down version of joml containing only the most necessary classes. However, there are better ways to shrink the final distributable and remove unneeded classes and methods (ProGuard, Maven Shade Plugin) and joml-mini is discontinued now. joml-2d provides classes for strictly 2D transformations. But it's rather inactive now, too, because there has yet to be a reported use/usecase of it. joml-geometry has been merged into joml master long ago, so also inactive. joml-fastmath has also been merged into joml master and can be activated via a Maven profile (see the pom.xml).

**Comment by Guichaguri** [comment]
Thank you :)
