### ISSUE TITLE
Rename Matrix4x3[f/d] to Matrix3x4[f/d] 

### ISSUE THREAD

**Issue by J-Ibarra** [JOML-CI/JOML#95]
A small bounding nothing serious, maybe it would be better to call matrix3x4 instead of matrix4x3, occasionally I get confused with this matrix by the nomenclature

you say:

>/**
 >* Contains the definition of an affine 4x3 matrix (4 columns, 3 rows) of floats, and associated functions to transform
> * it. The matrix is column-major to match OpenGL's interpretation, and it looks like this:
 >* <p>
 >*      m00  m10  m20  m30<br>
 >*      m01  m11  m21  m31<br>
 >*      m02  m12  m22  m32<br>
 >* 
 >* @author Richard Greenlees
 >* @author Kai Burjack
 >*/

- First read rows and next read the columns

maybe is:

>/**
 >* Contains the definition of an affine 3x4 matrix (3 rows, 4 columns) of floats, and associated functions to transform
> * it. The matrix is column-major to match OpenGL's interpretation, and it looks like this:
 >* <p>
 >*      m00  m10  m20  m30<br>
 >*      m01  m11  m21  m31<br>
 >*      m02  m12  m22  m32<br>
 >* 
 >* @author Richard Greenlees
 >* @author Kai Burjack
 >*/

Thanks, sorry for my English

**Comment by httpdigest** [comment]
No. 4x3 is by convention to mean 4 columns and 3 rows in this order. This is also the case for OpenGL/GLSL mat4x3 type. First comes the columns and then the rows.
This is just because the columns are usually what we care about, because they determine what unit vectors of the base axes are transformed into.
This is opposed to how Direct3D treats matrices, which is exactly the transpose.

**Comment by J-Ibarra** [comment]
Ok sorry, had not taken into account GLSL
Thank for You answer
