### ISSUE TITLE
Storing the top of MatrixStackf does not work

### ISSUE THREAD

**Issue by LukeFernandes** [JOML-CI/JOML#96]
For skinning, I want to perform the operation:

FinalBoneMatrix = MyMatrixStack

In order to store the current matrix of the stack in the matrix supplied in the left hand side. Currently the FinalBoneMatrix is unexpectedly affected by subsequent stack operations, which is not desirable. Even if a cast is used -

FinalBoneMatrix = (Matrix4f)MyMatrixStack

- the same problem arises.

Only 
FinalBoneMatrix = new Matrix4f( (Matrix4f)MyMatrixStack)
works as it is a full copy, but this is an unpleasant workaround as it increases GC pressure.

**Comment by httpdigest** [comment]
The matrix stack allocates a fixed number of matrices, where the count is given as constructor argument. Therefore all matrices in the stack always keep their identities, in order to be allocation free for all subsequent operations. You have to copy the matrix values if you want to preserve them across subsequent matrix stack modifications. However when doing a copy, you need not allocate a new matrix yourself everytime. You can use the very fast Matrix4f.set(Matrix4f/MatrixStack) method with the same target/this.

**Comment by LukeFernandes** [comment]
Thanks for clearing that up for me.
